### ISSUE TITLE
Link back to fec.gov  generates a server error

### ISSUE THREAD

**Issue by jwchumley** [18F/fec-eregs#365] opened 2017-10-27 18:11 UTC
https://fec-prod-eregs.app.cloud.gov/regulations/300-2/2017-annual-300#300-2-b-2

Click on the seal and get an error.

The link is to https://fec-prod-eregs.app.cloud.gov instead of https://www.fec.gov

**Comment by LindsayYoung** [comment] 2018-01-05 21:01
This is a duplicate of https://github.com/18F/fec-eregs/issues/364

Can we close this issue in favor of the other one?

**Comment by AmyKort** [comment] 2018-01-05 21:14
Closing in favor of https://github.com/18F/fec-eregs/issues/364

**Closed by AmyKort** 2018-01-05 21:14 UTC
Labels: Bug
