### ISSUE TITLE
Implement advisory opinion content

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-eregs#290] opened 2016-10-18 16:56 UTC
## Overview

We have advisory opinion content that's ready for design and implementation on betaFEC. :tada:

[Google Doc of approved advisory opinion content](https://docs.google.com/document/d/1XElM0QI3lP_9zrUi_TBqCnk8UcogoAkTLWbhBzPzgJs/edit#) :lock:

Thanks to @amykort and Cheryl for all their hard work on this.

I'm not 100% clear on what the design process is looking like these days for Legal. I know I want to tag in @jenniferthibault and @nickykrause to talk about this (Next sprint! I know we're all full for this one). I don't know which developers should be involved.
## Miscellaneous thoughts on design
- If you take a gander at the Google Document, it's about 3 Google Doc pages long, broken into five sections
- Because advisory opinions are complex, I think the content will make the most sense to users all together, in one place. So rather than spreading it onto several shorter checklist pages, I think it should be a long-ish piece of content with prominent headers for each section— I _don't think_ we'll want to use the checklist model from that's worked on other sections of the website (`Press`, `Registration and reporting`).
- The design will need to support a legal citations sidebar and a related topics sidebar. 
- I have no idea how and if this content should be integrated with the AO search, but I think what we decide to do here should make sense with our work in the `Enforcement` section, where we'll see 
## Existing AO page

<img width="1060" alt="screen shot 2016-10-18 at 11 27 01 am" src="https://cloud.githubusercontent.com/assets/10552702/19486929/f6cd1a92-9525-11e6-9f71-be2b902b4864.png">

**Comment by emileighoutlaw** [comment] 2016-10-18 16:59
A note from @porta-antiporta, that I don't want to lose when we move from draft to implementation:

> IMHO this content, once migrated, should also be included in the universal search / specific asset type search. i.e. Rather than just returning advisory opinions in the search, it should return results from the brochures, statistics etc. if there's a match. There will need to be design, API work to index this content once migrated, and UI to display search hits etc. to support this.

**Comment by jenniferthibault** [comment] 2016-10-19 01:04
@emileighoutlaw HOOOORAY!!!!! And round of high fives to Amy & Cheryl!

I just applied the newly minted `Needs grooming` label, channeling what @noahmanger is doing on the data tasks. Let's talk about this in design task grooming on Monday, which is now going to be for all design tasks across workstreams, and @adrianwebb is going to join in. #agile-design-stuff-and-things

One follow-up question for now: It looks like your last thought may have trailed off or gotten overwritten by the image in your first comment. What were you saying here?
> I think what we decide to do here should make sense with our work in the `Enforcement` section, where we'll see .........

**Comment by emileighoutlaw** [comment] 2016-10-20 16:31
Way to go me, trailing off mid sentence :roll_eyes: 

What I was thinking is that we should consider how design needs for this page are similar to other sections in `Legal resources`, where we could possibly unify design.

For example:
- `Advisory opinions` are comprised of introductory content, additional resources (PDFs and legal citations), and search capabilities. 
- `Statutes` are comprised of introductory content, additional resources (PDFs), and search capabilities.
- `Administrative fines` will also likely be comprised of introductory content,  additional resources (PDFs and legal citations), and a way to search Administrative Fine cases.

**Comment by emileighoutlaw** [comment] 2016-10-24 16:54
This is something we can start on this sprint so long as it doesn't require another research sprint

---
Steps to completion
- [ ] Revisit Ed's research
- [ ] Decide on design
- [ ] Implement

**Comment by jenniferthibault** [comment] 2016-11-01 00:03
In Reviewing earlier legal research, I learned there were often expressions toward favoring recency in many legal matters. Here's a few things that probably led to the placement of the `Pending advisory opinion requests` and the `Latest advisory opinions` elements:

> I check back every so often to see if they’ve been resolved. Or if an opinion has been handed down. I just see some— I read the one about Harry Reed for example. He’s wanting to hire an assistant to take care of everything. I wouldn’t know that, it’s not going to make the press. (U07)

> You should always put out today’s information. So people don’t confuse it. New rulings aren’t going to be in manuals— so you better have a place to go. (U07)

> we can't rely on the research and have to go to outside counsel more frequently, rather than relying on our research. we can't really have the confidence that what we found is the most recent law. (U10)

> We have to follow the law but the explanation of the law changes so fast. (U03)

Recency related to MURs:
> MuR database is extremely helpful when in the process of defending an enforcement action. Enforcement decisions are a reflection of what the Commission decided to do *at that time*. (U02)

I would say that it's a "nice to have" feature if we can work it into this page, but if pending views aren't available, we should somehow reinforce that the data will be viewable by year through the AO search filters, so the most recent could be viewed there, which you can see in the filter mockups in  https://github.com/18F/fec-eregs/issues/276

If we can provide the latest AOs, that would be a nice trailhead into the AO search by another route.

Working on mocking up designs next, and have dropped clarifying questions into the content document for @emileighoutlaw .

**Comment by jenniferthibault** [comment] 2016-11-03 23:24
Here's the first draft of what this implementation could look like. 
These new content modules make great use of our existing patterns, but uses more of them than we've had to accommodate before. This is going to lead to a few adjustments that will need to expand some of the existing patterns in new ways. Fun! (really!)
 
- Usually, for very long, multi-section pages we use a left side-nav pattern to help users understand what they'll be able to find on the page.
- Usually for citations, we use a right sidebar container to enable users to easily and quickly cross-reference in their research. 
  - BUT! We try to avoid combining the two patterns together since they both firmly hold the left and right lanes, and leave very little space for content when combined. Since this is an overview page, I think in this case the side nav wins, and the citations can be moved to more of a footnote position. (Confirmed with @emileighoutlaw )
- Sometimes, we use the bottom slab area for related content or next steps.
- Sometimes, we use the right-hand columns to link related content in context (like on Reg/Reporting landing with the campaign guides).
  - In this scenario, I think this approach is a better fit because the content is so long that it helps to keep the reader oriented by providing the related resource close to its' initial mention. (confirmed with @emileighoutlaw )

## Known open questions about the design, that we're ok with leaving open at this point and moving fwd with in mind:
- The page is long and has few clear calls to action besides directing users to the AO search. Could we find a more clear call to action for each section of the content?
 - Where else would be helpful to show users from here? (perhaps a way to link across other legal resources, and help people understand how they're related, but I'm putting that hypothesis in the parking lot)


## There are a few remaining to-do's before this is ready for implementation:

- [ ] Get citation links to betaFEC - @emileighoutlaw 
- [ ] Get citation summary titles - @emileighoutlaw 
- [ ] Design stylized cover icon for FEC Brochures - @jenniferthibault
- [ ] Review design with FEC: @emileighoutlaw how would you like to facilitate this?

Am I missing anything?


![ao landing 2 copy 4](https://cloud.githubusercontent.com/assets/11636908/19982662/52ea97a0-a1dd-11e6-85f3-31c6eb8fc355.png)

**Comment by emileighoutlaw** [comment] 2016-11-04 00:43
Woohoo! I love having such clear to dos!

Let me ask Amy how she'd like to review the design of this page. I don't think this is a task for the larger content manager group, but she may want to involve Cheryl in this one. I'll dig into that (and the things I still owe you) tomorrow ☺️

**Comment by nickykrause** [comment] 2016-11-04 16:04
Added @jenniferthibault's comment about open questions to a new issue in the testing repo: https://github.com/18F/fec-testing/issues/15

>The page is long and has few clear calls to action besides directing users to the AO search. Could we find a more clear call to action for each section of the content?

> Where else would be helpful to show users from here? (perhaps a way to link across other legal resources, and help people understand how they're related, but I'm putting that hypothesis in the parking lot)

**Comment by emileighoutlaw** [comment] 2016-11-17 15:26
I'm long overdue, but here are our citations @jenniferthibault 💟 : https://docs.google.com/document/d/1u5ZqI0tBF-p6E-UKKIDtNaDiW7STrtTE7hBgw9DM3YY/edit#

I've updated the list of citations, so it's not so long. It didn't make sense to me to have citations with the same name and link called out separately. I'll double check this with Amy.

**Comment by emileighoutlaw** [comment] 2016-11-17 16:17
Just paired with Amy. The citations in those documents are good to go, Jen :)

**Comment by emileighoutlaw** [comment] 2016-11-21 15:35
On Friday, my critique group helped me pinpoint what exactly about this content is bugging me. 

This page is trying to speak to three very different user groups:
- People who are looking up a specific thing and are very knowledgeable about advisory opinions
- People who are skimming for what's new and are very knowledgeable about advisory opinions
- People who have know very little about advisory opinions

**People who are looking up a specific thing**
Prominent search is what they need.

**People who are skimming for what's new**
Prominent feeds of pending opinions and recent opinions is what they need.

**People who have know very little**
This is the smallest user group, and the first sentence is _maybe all they need_ to get started.

The full page of text about the process is useful—  but I suspect it's equally helpful for users to _see_ feeds of pending advisory opinions and recent advisory opinions (the descriptions are all concrete examples of what an advisory opinion can be, whereas the advisory opinion process is complicated and messy). 

I know this is a big departure from what we have right now in the mockup, but I'd like to recommend cutting the content after the first sentence and creating a call to action for folks who want to [Learn more about the advisory opinion process](), which takes them to an interior page (similar to our registration and reporting checklist pages) with all the rest of the approved content. That would allow us to more prominently surface recent and pending opinions as well as the search. 

Thoughts @nickykrause @jenniferthibault ?

**Comment by AmyKort** [comment] 2016-11-21 15:40
@emileighoutlaw I think this is a great idea, serves the most users and does a lot to get folks where they need to go: "cutting the content after the first sentence and creating a call to action for folks who want to Learn more about the advisory opinion process, which takes them to an interior page (similar to our registration and reporting checklist pages) with all the rest of the approved content." 

Thanks for continuing to chip away at this one!

**Comment by jenniferthibault** [comment] 2016-11-21 19:27
I'm stoked about this idea. Glad to give it a go and revise mockups. 

We'll need to know what our criteria are for "recent" AO's are: 10 (or some other #) most recent? All AO's in the last last #X months?

**Comment by nickykrause** [comment] 2016-11-21 19:31
I agree - this makes a lot of sense. Hooray for critique groups!!! It's so nice to have fresh 👀  on our work  :tada:

**Comment by emileighoutlaw** [comment] 2016-11-21 20:21
Woohoo! I think our expert @amykort is the person to ask about what our criteria for "recent" should be. Any thoughts?

**Comment by AmyKort** [comment] 2016-11-21 20:33
I need a frame of reference for what's a useful number from a design perspective. A really unscientific look at the past three years' worth of opinions suggests that 10 AOs represent about 4 or 5 months worth of activity, except sometimes we issue 10 opinions in 6 weeks. Generally, AOs come in irregularly, so there are busy spikes and less busy times. I don't know whether that argues in favor of having a set number show up.

**Comment by jenniferthibault** [comment] 2016-11-21 23:05
Immensely helpful @AmyKort — and I think we can use design here to represent just what it is: irregular. I tapped Jeremy to help think through some logic here, and he gave the following idea. 

- Show two months' worth of AOs. When there are spikes, this might be 10+, but probably not 20, and users can tell it's a busy time. When there are lulls, there might be only a couple. This variance is totally ok, and we can add content to help people understand how we're showing what we're showing.
- Give people a way to view all of the AOs with relative high priority. This should be easy for users to find.

I'm going to work on mocking this up, and could have something showing what this looks like by tomorrow.

**Comment by jenniferthibault** [comment] 2016-11-22 16:05
Here's a first take at what it could look like as two pages. 
- There's a few areas where I've called attention to items that seemed to be needed for the flow/introduction of sections on the AO landing page. I took a first stab, but consider that a draft starting point 😄 
- It also seemed like we needed a new title for the second page, but I'm not sure what that should be.
- For the Pending & Latest lists, I used the feed pattern that we've established in Latest Updates & Press, and will be continuing on for lists of archived documents. 

![ao landing 2 copy 6](https://cloud.githubusercontent.com/assets/11636908/20531043/6cbb25e4-b0a3-11e6-8f5a-78250fc1847a.png)

![ao landing 2 copy 7](https://cloud.githubusercontent.com/assets/11636908/20531047/71308e2a-b0a3-11e6-8d3e-ffe0185dcb12.png)

Thoughts?

**Comment by nickykrause** [comment] 2016-11-22 16:46
This approach is already making a lot more sense, I think! It seems like a cleaner approach, which can connect users to their desired tasks more quickly. The other thing I am realizing is that the page offers a feed of "latest updates" about AOs. We agreed that AOs shouldn't appear in the "latest updates" section, but I think it is nice that such a feed exists somewhere, and in a relevant place.

(Also, Jen, your inclusion of the little pictures of Emileigh really made me laugh. 😆 )

**Comment by emileighoutlaw** [comment] 2016-11-22 19:58
I am in love with this approach (especially the new brochure icon).

Pinging @amykort to see if you think we're okay to call this page "The advisory opinion process." I can't imagine that being an issue, but I trust your gut more than mine :)

**Comment by AmyKort** [comment] 2016-11-22 20:03
I like it.

**Comment by emileighoutlaw** [comment] 2016-11-22 20:25
Awesome! That leaves only one small section for us to think about content-wise:

Since we moved all our supporting content to an interior page, we'll need some microcopy on the landing page to introduce "Pending advisory opinion requests"  and "Latest advisory opinions."

Jen has a great first recommendation in the mockup. With some minor adjustments, I'd recommend we have:
> **Pending advisory opinion requests**
> Advisory opinion requests have been reviewed by the Office of General Counsel and are open to comment for ten days after they're made public.
> [Learn how to comment]()(button that takes users to our inside section on requests)

_^^ This language is almost exactly the brochure. Can we go with it, or would we need additional approval?_

(A thought— if we tell people they have a limited timeframe in which to comment on a request, is there a way to surface the date the request was made public in this feed? Maybe a dev question?)

> **Recent advisory opinions issued**
> The Commission issues an advisory opinion when four or more Commissioners vote to approve it. These votes almost always occur during an open meeting. 
> [Explore all advisory opinions]()(button that takes users to our advanced search)

_^^ This language is pulled exactly from the brochure. I don't believe we need additional review of it_

**Comment by jenniferthibault** [comment] 2016-11-22 21:10
Mindreader on the commenting deadline! I must have switched contexts to something else and forgot, but I also think it would be really useful to give users a sense of action timeline. 

Here's what that could look like:

![screen shot 2016-11-22 at 4 08 07 pm](https://cloud.githubusercontent.com/assets/11636908/20542086/172c1072-b0ce-11e6-89b8-a2e0b6c2687a.png)

**Comment by nickykrause** [comment] 2016-11-22 22:22
@jenniferthibault - How do users get to the place where they can make comments? Would the canonical AO page have that link, or could we include it here? (We don't have pending AOs up yet on beta, so I assume this hasn't been decided yet?)

**Comment by jenniferthibault** [comment] 2016-11-23 04:04
Users can only comment on AO requests by mail, so it's not functionality we need to invent or design. 

The link from the "Learn how to comment" button in the pending section on the first page would link to the relevant section on "The advisory opinion process" page (second screenshot above).

**Comment by AmyKort** [comment] 2016-11-29 14:53
Little tweak to the content about pending AORs:

How about:
Once the Office of General Counsel has determined that an advisory opinion request meets all of the requirements to move forward for consideration by the Commission, the request is made public and is available for public comment for ten days.

**Comment by emileighoutlaw** [comment] 2016-11-29 14:59
I think that's beautiful @AmyKort ! So our final microcopy for that landing page is:

> **Pending advisory opinion requests**
Once the Office of General Counsel has determined that an advisory opinion request meets all of the requirements to move forward for consideration by the Commission, the request is made public and is available for public comment for ten days.
[Learn how to comment]()(button that takes users to our inside section on requests)


> **Recent advisory opinions issued**
The Commission issues an advisory opinion when four or more Commissioners vote to approve it. These votes almost always occur during an open meeting.
[Explore all advisory opinions]()(button that takes users to our advanced search)

And we are truly ready for implementation now, I believe.

**Comment by xtine** [comment] 2016-12-01 22:18
I am going to start implementing this. I just have questions about where all the links go? I see:

- Advisory Opinion Brochure
- Search advisory opinion requests
- Draft advisory opinion procedures
- Open meetings calendar
- Advisory opinion statistics PDF
- open meeting of the Commission (under Issuing and advisory opinion)
- links under Legal Citations

cc: @emileighoutlaw

**Comment by emileighoutlaw** [comment] 2016-12-01 22:26
- Advisory Opinion Brochure: http://www.fec.gov/pages/brochures/ao.shtml
Search advisory opinion requests: https://beta.fec.gov/data/legal/advisory-opinions/
- Draft advisory opinion procedures: _I think this might be a mistake. I don't have a link for this in my content draft. Did @jenniferthibault have something clever in mind for this that I don't remember?_
- Open meetings calendar: https://beta.fec.gov/calendar/
- Advisory opinion statistics PDF: http://www.fec.gov/law/policy/enforcement/2009/ao05-09.pdf
- Open meeting of the Commission (under Issuing and advisory opinion): https://beta.fec.gov/calendar/


All legal citations links are in this [Google Doc](https://docs.google.com/document/d/1u5ZqI0tBF-p6E-UKKIDtNaDiW7STrtTE7hBgw9DM3YY/edit#heading=h.p4yz44y54e0r) 🔒 . I can paste them individually into this issue, if you'd prefer that 💟

**Comment by xtine** [comment] 2016-12-01 22:28
@emileighoutlaw: thanks! I missed that citations doc.

**Comment by emileighoutlaw** [comment] 2016-12-01 22:30
I think I hadn't ever shared it with you, so no way you could have found it! :upside_down_face:

**Comment by jenniferthibault** [comment] 2016-12-02 02:09
I think I may have garbled a copy/paste on `Draft advisory opinion procedures`...

Looking back on @emileighoutlaw's original [Google Doc of approved advisory opinion content](https://docs.google.com/document/d/1XElM0QI3lP_9zrUi_TBqCnk8UcogoAkTLWbhBzPzgJs/edit#) :lock: I think it's supposed to be `Search draft answers to advisory opinions`. Here's her comment:

> Is it possible to link from here to the advisory opinion advanced search, pre-filtered for "draft documents" in the "Document type" search

I think that will be dependent on this issue: [Implement initial AO filters on front-end](https://github.com/18F/openFEC-web-app/issues/1705), since it should direct users to a filtered view of the AO search results .

It should also probably look like this:

![screen shot 2016-12-01 at 9 08 00 pm](https://cloud.githubusercontent.com/assets/11636908/20820593/53294034-b80a-11e6-9472-be197a4204ad.png)


@xtine for implementation, I know I need to export you a few icons. Can do tomorrow.

**Comment by noahmanger** [comment] 2016-12-02 02:15
I just realized that we're not currently showing the `Pending advisory opinions` or `Latest advisory opinions` on the site. Do we have pending ones? And are latest just the most recent ones closed? Do we have the ability to sort by date closed? cc @anthonygarvan

**Comment by jenniferthibault** [comment] 2016-12-02 14:51
> Do we have pending ones? 
Yes. 
I can't get you the link because it's nota permalink, but they are linked from FEC.gov's page here: http://saos.fec.gov/saos/searchao

> Are the latest jus the most recent ones closed?
Yes. AOs closed in the last two months. For rationale: https://github.com/18F/fec-eregs/issues/290#issuecomment-262096212

**Comment by xtine** [comment] 2016-12-02 17:14
To add on @noahmanger's comment about Pending/Recent advisory opinions, where is that data coming from, the cms, another database, or hardcoded?

**Comment by jenniferthibault** [comment] 2016-12-02 17:31
@xtine can you talk with @anthonygarvan about that? I know he dug into those questions before and has the answers.... or leads.

**Comment by anthonygarvan** [comment] 2016-12-02 17:40
That data would come from elasticsearch, which in turn comes from a data dump into postgres from FEC. And yes, AOs have an "ISSUE_DATE" column which I believe is the close date, which we could sort by.

**Comment by noahmanger** [comment] 2016-12-16 00:00
Ok, these pages have been largely implemented and merged in. There's a remaining task to add the pending AOs, but it's tracked in a separate issue https://github.com/18F/openFEC-web-app/issues/1747

**Closed by noahmanger** 2016-12-16 00:00 UTC
Labels: Dashboard: Legal, Mothership, Work: Front-end
