### ISSUE TITLE
Improve search result inclusiveness of MURs

### ISSUE THREAD

**Issue by adrianwebb** [18F/fec-eregs#293] opened 2016-10-25 16:10 UTC
Comment: I explored the MUR search system on the beta website at this link, https://fec-stage-proxy.18f.gov/data/legal/matter-under-review/1000/.  I performed a search for matters involving embezzlement, an area I know fairly well.

Searching using a term returned results that were both over-inclusive and under-inclusive. 
 
**Under-inclusive**.  For example, I searched the term “embezzlement” (without quotes)  and the search returned 61 cases.  The search did not return at least three MURs involving embezzlement that I’m aware of:  MURs 6597 (Kindee Durkee); 6526 (Cora Carper) and 6188 (San Antonio Police Officers Assoc. PAC/Clifford Morgan).  In all three cases the words “embezzlement” and “embezzled” appear in the First General Counsel’s Report yet none of this cases come up in the search.

I also searched “embezzle” without quotes which returned only 21 cases, some of which did not appear in the “embezzlement search (MURs 2453, 5182, 456, 373).  I would expect a search for the term “embezzle” to pull up documents with “embezzlement” since the former is contained in the latter.
 
**Over-inclusive**.  I checked some of the 61 cases came up in the embezzlement search that did not seem familiar to me and they were not embezzlement cases.  Following are three examples, the “matches” for the term in MUR 6031 reads:

MUR #6031
HAGAN SENATE COMMITTEE INC
… , Embezzlement, Disclosure," MONEY & POL. REP. (BNA) (Jan. 02,2009) ("[Commissioners voted to drop [the …
Date closed: 2009
Subject: Contributions-Excessive; Reporting
 
MUR 6031 involved excessive contributions, untimely-filed 48 hour notice reports and failure to report contributor identification information. The “match” seems to be a citation I could not locate in the case documents.
 
MUR #5957
COMMITTEE TO ELECT SEKHON FOR CONGRESS
… , "GOP Members Deadlock FEC, Undermining Position of 527s, Embezzlement, Disclosure," MONEY & POL. REP …
Date closed: 2008
Subject: Reporting
 
MUR 5957 involved the failure to provide adequate contributor information and not embezzlement.
 
MUR #5219
IUE, LOCAL UNION #323
… election of union officers) or criminal matters (such as embezzlement of union funds). July 1997 … election and order a new election under OLMS supervision. OLMS conducts embezzlement investigations to … possible embezzlement violations by union' officers or employees to the U.S. Attorney, who decides if … criminal prosecution is warranted. Persons who have been convicted of embezzlement or certain other …
Date closed: 2001
 
MUR 5219 was generated by a one-page referral from an outside agency of a prohibited contribution to a political committee from a labor union.  The “match” from an attachment to the referral that describes the law the referring agency administers and it is irrelevant to the subject of the case.
 
It may help limit over-inclusiveness if searches pulled from only OGC prepared documents such as the First General Counsel’s Report, General Counsel’s Reports, Conciliation Agreement, General Counsel’s Brief and Commission-prepared documents such as Statements of Reason.

For further comments, see: https://docs.google.com/document/d/1eVFGVEDJEOESyjOptWO58uYJkg7NB26xF6rK9fCQE6E/edit

**Comment by adrianwebb** [comment] 2016-10-25 16:22
Related: https://github.com/18F/fec-eregs/issues/106

**Comment by adrianwebb** [comment] 2016-10-25 16:26
Possibly related: https://github.com/18F/fec-eregs/issues/267

**Comment by vrajmohan** [comment] 2016-10-26 12:05
As predicted, MUR#6031 mentions embezzlement in a citation in a footnote in one of the docs - https://cg-069252d5-5311-406c-9d08-a09e59f6b9c8.s3.amazonaws.com/legal/murs/current/78713.pdf.

**Comment by anthonygarvan** [comment] 2016-10-27 15:40
@vrajmohan and I checked MURs 6597 (Kindee Durkee); 6526 (Cora Carper) and 6188 (San Antonio Police Officers Assoc. PAC/Clifford Morgan). All of these MURs could not be OCR'ed by FEC. There were 7,576 MURS that could not be OCR'ed, these are among those. This is a known issue we have raised, we are waiting for resolution from FEC.

**Comment by anthonygarvan** [comment] 2016-10-27 15:47
In terms of "over-inclusive", these documents do in fact contain the term "embezzlement". 
- [5957](https://cg-069252d5-5311-406c-9d08-a09e59f6b9c8.s3.amazonaws.com/legal/murs/current/97955.pdf#page=15), for example, has it in a footnote.

**Comment by anthonygarvan** [comment] 2016-10-27 15:51
These are not technical problems. The search is functioning as designed. Rather, we need to give users a way to filter if a keyword match represents a truly relevant document or if it just mentions the word. Possible ways to do this: including more / complete list of highlighted matches, displaying # hits.

**Comment by nickykrause** [comment] 2016-10-27 20:19
@anthonygarvan: I was just watching this issue, and I wanted to check my understanding about the over-inclusiveness of the search. Here's my understanding - can you confirm if it's accurate? (I realize I am essentially just repeating some things you've said, but in different words. Bear with me, please!)

(cc: @jenniferthibault)
 
**Reported problem** 
> [MUR search results are] over-inclusive. I checked some of the 61 cases came up in the embezzlement search that did not seem familiar to me and they were not embezzlement cases.

This user searched for "embezzlement" and was under the impression that there were too many results returned, including results that did not appear (to the user) to deal with "embezzlement"

**Hypothesis**
The search process is malfunctioning somehow. It is returning matches for the term "embezzlement" when matches do not actually exist.

**Investigation**
Tony looked into the specific cases mentioned by the user, and it turns out that the questionable results did in fact contain the term "embezzlement." However, embezzlement was not necessarily an important topic within those results.

**Diagnosis**
The search is not malfunctioning; it is returning results that contain the word "embezzlement," as it should. It was not designed to facilitate more nuanced searching beyond the search term matching.

 **Takeaway**
Essentially, this user has not identified a bug in the search, but rather a need for additional search refinement features that assist the user in drilling down to search terms that are relevant to them.

**Comment by nickykrause** [comment] 2016-10-27 20:20
correction: drilling down to search results* that are relevant to them (not "search terms")

**Comment by nickykrause** [comment] 2016-10-27 20:30
One more correction, because I think I went too far by saying that the user identified the need for refinement features. That statement may be too far down the road on a solution, when, really, that might not be the best way to address the problem.

So, perhaps it makes more sense to say it this way:

**Takeaway**
This user has not identified a bug in the search. 

Instead, the user's comment highlights the following problem with the search experience: The user's definition of what constitutes a relevant "match" is not aligned with how the search is designed to function.

**Comment by nickykrause** [comment] 2016-10-28 20:23
(cc: @jenniferthibault, @emileighoutlaw, @adrianwebb)
   
The design team just met to discuss legal issues and to remove any blocks that may exist from us this sprint. Here is a summary of what we discussed for the two components of this issue (i.e., "under-inclusive" results and "over-inclusive" results):

**Under-inclusive**
Our current understanding is that the issue of under-inclusive results will be solved by turning on stemming, as @anthonygarvan mentioned today in Slack. 

**Over-inclusive**
This does not appear to be a technical issue, as it seems that the functionality is working as designed. However, there is a disconnect between what the search is doing (and/or what the interface is displaying) and what the user expects.

Given that the functionality is working, it doesn't seem that the over-inclusiveness issue should delay the release. 

Also, to add clarity to these issues, we think it would make sense to close this issue once we implement the stemming functionality to resolve under-inclusiveness, and then we can deal with the perceived "over-inclusiveness" issue (which is actually a misaligned user expectation) somewhere else. We suggest dealing with as a part of issue #296 - "Help users better determine if the cases returned are relevant."

**Comment by jenniferthibault** [comment] 2016-10-28 21:04
Nicky got the background 💯 

I'm going to close this issue and want to be uber, super, 100% clear why. 

- We think that turning on stemming should be tracked through a pre-existing issue, where Porta called it "Derivative search" https://github.com/18F/fec-eregs/issues/106 

- We are going to track all factors pertaining to result relevance in #296 in order to keep the number of issues down.  

Holler with questions or if you feel this shouldn't be closed!

**Closed by jenniferthibault** 2016-10-28 21:04 UTC
Labels: Dashboard: Legal
